const categories = [
  {
    name: 'Food',
    image: 'food.png',
    icon: 'foodicon.png',
  },
  {
    name: 'Animals',
    image: 'animals.png',
    icon: 'animalsicon.png',
  },
  {
    name: 'Clothes',
    image: 'clothes.png',
    icon: 'clothesicon.png',
  },
  {
    name: 'Kitchen',
    image: 'kitchen.png',
    icon: 'kitchenicon.png',
  },
  {
    name: 'Sport',
    image: 'sport.png',
    icon: 'sporticon.png',
  },
  {
    name: 'Building',
    image: 'building.png',
    icon: 'buildingicon.png',
  },
  {
    name: 'Appliances',
    image: 'appliances.png',
    icon: 'appliancesicon.png',
  },
  {
    name: 'Transport',
    image: 'transport.png',
    icon: 'transporticon.png',
  },
];

const cards = [
  [
    {
      word: 'bacon',
      translation: 'бекон',
      image: 'food/bacon.jpg',
      audioSrc: 'audio/bacon.mp3',
    },
    {
      word: 'carrot',
      translation: 'морковка',
      image: 'food/carrot.jpg',
      audioSrc: 'audio/carrot.mp3',
    },
    {
      word: 'cheese',
      translation: 'сыр',
      image: 'food/cheese.jpg',
      audioSrc: 'audio/cheese.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'food/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
    },
    {
      word: 'coffee',
      translation: 'кофе',
      image: 'food/coffee.jpg',
      audioSrc: 'audio/coffee.mp3',
    },
    {
      word: 'donut',
      translation: 'пончик',
      image: 'food/donut.jpg',
      audioSrc: 'audio/donut.mp3',
    },
    {
      word: 'egg',
      translation: 'яйцо',
      image: 'food/egg.jpg',
      audioSrc: 'audio/egg.mp3',
    },
    {
      word: 'sandwich',
      translation: 'бутерброд',
      image: 'food/sandwich.jpg',
      audioSrc: 'audio/sandwich.mp3',
    },
  ],
  [
    {
      word: 'bear',
      translation: 'медведь',
      image: 'animals/bear.jpg',
      audioSrc: 'audio/bear.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'animals/pig.jpg',
      audioSrc: 'audio/pig.mp3',
    },
    {
      word: 'cat',
      translation: 'кот',
      image: 'animals/cat.jpg',
      audioSrc: 'audio/cat.mp3',
    },
    {
      word: 'penguin',
      translation: 'пингвин',
      image: 'animals/penguin.jpg',
      audioSrc: 'audio/penguin.mp3',
    },
    {
      word: 'elephant',
      translation: 'слон',
      image: 'animals/elephant.jpg',
      audioSrc: 'audio/elephant.mp3',
    },
    {
      word: 'monkey',
      translation: 'обезьяна',
      image: 'animals/monkey.jpg',
      audioSrc: 'audio/monkey.mp3',
    },
    {
      word: 'fox',
      translation: 'лиса',
      image: 'animals/fox.jpg',
      audioSrc: 'audio/fox.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'animals/lion.jpg',
      audioSrc: 'audio/lion.mp3',
    },
  ],
  [
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'clothes/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
    },
    {
      word: 'undershirt',
      translation: 'майка',
      image: 'clothes/undershirt.jpg',
      audioSrc: 'audio/undershirt.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'clothes/dress.jpg',
      audioSrc: 'audio/dress.mp3',
    },
    {
      word: 'tie',
      translation: 'галстук',
      image: 'clothes/tie.jpg',
      audioSrc: 'audio/tie.mp3',
    },
    {
      word: 'hat',
      translation: 'шляпа',
      image: 'clothes/hat.jpg',
      audioSrc: 'audio/hat.mp3',
    },
    {
      word: 'sock',
      translation: 'носок',
      image: 'clothes/sock.jpg',
      audioSrc: 'audio/sock.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'clothes/pants.jpg',
      audioSrc: 'audio/pants.mp3',
    },
    {
      word: 'slippers',
      translation: 'шлепанцы',
      image: 'clothes/slippers.jpg',
      audioSrc: 'audio/slippers.mp3',
    },
  ],
  [
    {
      word: 'cup',
      translation: 'чашка',
      image: 'kitchen/cup.jpg',
      audioSrc: 'audio/cup.mp3',
    },
    {
      word: 'teapot',
      translation: 'чайник',
      image: 'kitchen/teapot.jpg',
      audioSrc: 'audio/teapot.mp3',
    },
    {
      word: 'fork',
      translation: 'вилка',
      image: 'kitchen/fork.jpg',
      audioSrc: 'audio/fork.mp3',
    },
    {
      word: 'spoon',
      translation: 'ложка',
      image: 'kitchen/spoon.jpg',
      audioSrc: 'audio/spoon.mp3',
    },
    {
      word: 'grater',
      translation: 'тёрка',
      image: 'kitchen/grater.jpg',
      audioSrc: 'audio/grater.mp3',
    },
    {
      word: 'scoop',
      translation: 'черпак',
      image: 'kitchen/scoop.jpg',
      audioSrc: 'audio/scoop.mp3',
    },
    {
      word: 'knife',
      translation: 'нож',
      image: 'kitchen/knife.jpg',
      audioSrc: 'audio/knife.mp3',
    },
    {
      word: 'saucepan',
      translation: 'кастрюля',
      image: 'kitchen/saucepan.jpg',
      audioSrc: 'audio/saucepan.mp3',
    },
  ],
  [
    {
      word: 'ball',
      translation: 'мяч',
      image: 'sport/ball.jpg',
      audioSrc: 'audio/ball.mp3',
    },
    {
      word: 'sneaker',
      translation: 'кроссовок',
      image: 'sport/sneaker.jpg',
      audioSrc: 'audio/sneaker.mp3',
    },
    {
      word: 'boxing gloves',
      translation: 'боксерские перчатки',
      image: 'sport/boxing-gloves.jpg',
      audioSrc: 'audio/boxing-gloves.mp3',
    },
    {
      word: 'skates',
      translation: 'коньки',
      image: 'sport/skates.jpg',
      audioSrc: 'audio/skates.mp3',
    },
    {
      word: 'dumbbell',
      translation: 'гантеля',
      image: 'sport/dumbbell.jpg',
      audioSrc: 'audio/dumbbell.mp3',
    },
    {
      word: 'racket',
      translation: 'ракетка',
      image: 'sport/racket.jpg',
      audioSrc: 'audio/racket.mp3',
    },
    {
      word: 'helmet',
      translation: 'шлем',
      image: 'sport/helmet.jpg',
      audioSrc: 'audio/helmet.mp3',
    },
    {
      word: 'medal',
      translation: 'медаль',
      image: 'sport/medal.jpg',
      audioSrc: 'audio/medal.mp3',
    },
  ],
  [
    {
      word: 'brush',
      translation: 'кисть',
      image: 'building/brush.jpg',
      audioSrc: 'audio/brush.mp3',
    },
    {
      word: 'wrench',
      translation: 'гаечный ключ',
      image: 'building/wrench.jpg',
      audioSrc: 'audio/wrench.mp3',
    },
    {
      word: 'hammer',
      translation: 'молоток',
      image: 'building/hammer.jpg',
      audioSrc: 'audio/hammer.mp3',
    },
    {
      word: 'tape',
      translation: 'рулетка',
      image: 'building/tape.jpg',
      audioSrc: 'audio/tape.mp3',
    },
    {
      word: 'pliers',
      translation: 'плоскогубцы',
      image: 'building/pliers.jpg',
      audioSrc: 'audio/pliers.mp3',
    },
    {
      word: 'shovel',
      translation: 'лопата',
      image: 'building/shovel.jpg',
      audioSrc: 'audio/shovel.mp3',
    },
    {
      word: 'saw',
      translation: 'пила',
      image: 'building/saw.jpg',
      audioSrc: 'audio/saw.mp3',
    },
    {
      word: 'screwdriver',
      translation: 'отвёртка',
      image: 'building/screwdriver.jpg',
      audioSrc: 'audio/screwdriver.mp3',
    },
  ],
  [
    {
      word: 'coffee machine',
      translation: 'кофеварка',
      image: 'appliances/coffee-machine.jpg',
      audioSrc: 'audio/coffee-machine.mp3',
    },
    {
      word: 'toaster',
      translation: 'тостер',
      image: 'appliances/toaster.jpg',
      audioSrc: 'audio/toaster.mp3',
    },
    {
      word: 'washing machine',
      translation: 'стиральная машина',
      image: 'appliances/washing-machine.jpg',
      audioSrc: 'audio/washing-machine.mp3',
    },
    {
      word: 'iron',
      translation: 'утюг',
      image: 'appliances/iron.jpg',
      audioSrc: 'audio/iron.mp3',
    },
    {
      word: 'oven',
      translation: 'духовка',
      image: 'appliances/oven.jpg',
      audioSrc: 'audio/oven.mp3',
    },
    {
      word: 'multicooker',
      translation: 'мультиварка',
      image: 'appliances/multicooker.jpg',
      audioSrc: 'audio/multicooker.mp3',
    },
    {
      word: 'kettle',
      translation: 'чайник',
      image: 'appliances/kettle.jpg',
      audioSrc: 'audio/kettle.mp3',
    },
    {
      word: 'microwave oven',
      translation: 'микроволновка',
      image: 'appliances/microwave-oven.jpg',
      audioSrc: 'audio/microwave-oven.mp3',
    },
  ],
  [
    {
      word: 'airplane',
      translation: 'самолёт',
      image: 'transport/airplane.jpg',
      audioSrc: 'audio/airplane.mp3',
    },
    {
      word: 'truck',
      translation: 'грузовик',
      image: 'transport/truck.jpg',
      audioSrc: 'audio/truck.mp3',
    },
    {
      word: 'bicycle',
      translation: 'велосипед',
      image: 'transport/bicycle.jpg',
      audioSrc: 'audio/bicycle.mp3',
    },
    {
      word: 'train',
      translation: 'поезд',
      image: 'transport/train.jpg',
      audioSrc: 'audio/train.mp3',
    },
    {
      word: 'car',
      translation: 'автомобиль',
      image: 'transport/car.jpg',
      audioSrc: 'audio/car.mp3',
    },
    {
      word: 'ship',
      translation: 'корабль',
      image: 'transport/ship.jpg',
      audioSrc: 'audio/ship.mp3',
    },
    {
      word: 'helicopter',
      translation: 'вертолет',
      image: 'transport/helicopter.jpg',
      audioSrc: 'audio/helicopter.mp3',
    },
    {
      word: 'motorcycle',
      translation: 'мотоцикл',
      image: 'transport/motorcycle.jpg',
      audioSrc: 'audio/motorcycle.mp3',
    },
  ],
];

export { categories, cards };
